### ISSUE TITLE
enhancements

### ISSUE THREAD

**Issue by nchase** [twinlabs/forum#118]
Stuff that should be user-configurable:
- [ ] Default number of threads displayed on index page
- [ ] Default number of posts displayed per thread
- [ ] Autoscroll on new post (true/false)
- [ ] Displayname – just their own, to start. might be a good idea to keep a list of user_id -> displayname mappings per-user in the future. if we do that, we can avoid the problem where people change their displayname and users suddenly have no idea who they're talking to.
- [ ] forum's title

---

Other enhancements:
- [ ] it would be great to have a horizontal line in the UI between old posts and new posts.
- [ ] "Does the forum have a feature where it loads all posts after the last one that you saw in a thread? If so, can you make it so it loads all posts since the last one you saw, but also the last one you saw, so you can tell you aren't missing anything?"
- [ ] smarter emoji lookup (#100)
- [ ] clean up sessions (#148)
- [ ] attachments (#119)
- [ ] reset password behavior (#176)

**Comment by jasonbekolay** [comment]
Let users change their display names

**Comment by nchase** [comment]
yep, that's the one I was hoping someone would say! didn't want to add that to the list because I figured someone else would :)

**Comment by nchase** [comment]
So here are two possibilities I'm thinking of:

1. a `user_settings` table with each one of these options as a column and then a `user_id` coumn
2. the same as above, but instead of a separate table, we put this info in the existing `forum_user` table.

@jasonbekolay do you have any thoughts or suggestions?

**Comment by jasonbekolay** [comment]
Just add stuff to the forum_user table, I don't see a good reason for a separate table
